FLASK_APP=app
FLASK_ENV=development

SECRET_KEY=rxKMR0MTqqhn5vybYnjLaekJm7aLMR
JWT_SECRET_KEY=rMUZWWpD46Nyv1Do9uH3LAFFgDUfy61Nvkaxz62A

DATABASE_URL=postgresql://touchline_admin:touchline_admin@localhost/touchline_dev
API_KEY=bc5c0860d9d43d604063b03b996ffa18

AZURE_STORAGE_ACCOUNT_NAME=touchlinedevstorage
AZURE_STORAGE_ACCOUNT_KEY=hq9oILiazEtAPIiRK8W1fz3oHak8orPksP5wUH/HSw19IY/ta8lBTjTbioaETFF4dqmzWKmWhfRE+AStLbM+ZA==
AZURE_CONTAINER_NAME=touchline-dev-pics
